# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/f1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/f1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fprotos/f1.proto\x12\x02\x66\x31\">\n\x04Pneu\x12\x13\n\x0btemperatura\x18\x01 \x01(\x02\x12\x10\n\x08\x64\x65sgaste\x18\x02 \x01(\x02\x12\x0f\n\x07pressao\x18\x03 \x01(\x02\"\xd3\x01\n\nDadosCarro\x12\x10\n\x08\x63\x61rro_id\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\t\x12\x12\n\nvelocidade\x18\x03 \x01(\x02\x12\r\n\x05volta\x18\x04 \x01(\x05\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x19\n\x07pneu_fl\x18\x06 \x01(\x0b\x32\x08.f1.Pneu\x12\x19\n\x07pneu_fr\x18\x07 \x01(\x0b\x32\x08.f1.Pneu\x12\x19\n\x07pneu_rl\x18\x08 \x01(\x0b\x32\x08.f1.Pneu\x12\x19\n\x07pneu_rr\x18\t \x01(\x0b\x32\x08.f1.Pneu\"-\n\x08Resposta\x12\x10\n\x08mensagem\x18\x01 \x01(\t\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x32\x42\n\rMonitoramento\x12\x31\n\x0f\x45nviarDadosPneu\x12\x0e.f1.DadosCarro\x1a\x0c.f1.Resposta\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.f1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PNEU']._serialized_start=23
  _globals['_PNEU']._serialized_end=85
  _globals['_DADOSCARRO']._serialized_start=88
  _globals['_DADOSCARRO']._serialized_end=299
  _globals['_RESPOSTA']._serialized_start=301
  _globals['_RESPOSTA']._serialized_end=346
  _globals['_MONITORAMENTO']._serialized_start=348
  _globals['_MONITORAMENTO']._serialized_end=414
# @@protoc_insertion_point(module_scope)
